[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Recordatorio automático cada 2 horas
[functions."recordatorio"]
  schedule = "0 */2 * * *"